### ISSUE TITLE
0.5.0-1 on Linux Mint 20.2 Cinnamon (installed using ppa:apandada1/blanket)  doesn't work

### ISSUE THREAD

**Issue by arax-1238** [rafaelmardojai/blanket#188]
Hi, thanks for you great work! 
This morning **update to 0.5**  throught ppa:apandada1/blanket  **seem not to work...**

io@glutin:~$ blanket
Traceback (most recent call last):
  File "/usr/share/blanket/blanket/presets.py", line 48, in __init__
    self.presets_list.bind_model(self.model, self._create_widget)
AttributeError: 'Child' object has no attribute 'bind_model'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] File o directory non esistente: '/var/crash/_usr_bin_blanket.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/share/blanket/blanket/presets.py", line 48, in __init__
    self.presets_list.bind_model(self.model, self._create_widget)
AttributeError: 'Child' object has no attribute 'bind_model'
Traceback (most recent call last):
  File "/usr/share/blanket/blanket/main.py", line 140, in do_activate
    self.window = BlanketWindow(self.mainplayer, application=self)
  File "/usr/share/blanket/blanket/window.py", line 123, in __init__
    self.setup()
  File "/usr/share/blanket/blanket/window.py", line 151, in setup
    self.setup_presets()
  File "/usr/share/blanket/blanket/window.py", line 168, in setup_presets
    self.update_title(self.presets_chooser.selected)
  File "/usr/share/blanket/blanket/window.py", line 254, in update_title
    if preset.id != Settings.get().default_preset:
AttributeError: 'NoneType' object has no attribute 'id'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] File o directory non esistente: '/var/crash/_usr_bin_blanket.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/share/blanket/blanket/main.py", line 140, in do_activate
    self.window = BlanketWindow(self.mainplayer, application=self)
  File "/usr/share/blanket/blanket/window.py", line 123, in __init__
    self.setup()
  File "/usr/share/blanket/blanket/window.py", line 151, in setup
    self.setup_presets()
  File "/usr/share/blanket/blanket/window.py", line 168, in setup_presets
    self.update_title(self.presets_chooser.selected)
  File "/usr/share/blanket/blanket/window.py", line 254, in update_title
    if preset.id != Settings.get().default_preset:
AttributeError: 'NoneType' object has no attribute 'id'

**Comment by mskf1383** [comment]
I have problem with new version too (the ppa package for ubuntu)

**Comment by rafaelmardojai** [comment]
@apandada1 Any clue on why is this happening?

**Comment by apandada1** [comment]
I can reproduce this in KDE Neon. I should have built and tested it locally before pushing to the PPA.

The same issue is present when I build from source (can anyone reproduce this?_

**Comment by apandada1** [comment]
I cannot reproduce this issue when I build from source in Manjaro (python 3.9). Is python 3.8 in Ubuntu 20.04 the issue here?

**Comment by rafaelmardojai** [comment]
Maybe I'm using some new feature from python or pygobject? I don't think I am, but could be.

**Comment by apandada1** [comment]
I will build from the commits one by one, and try to find where the issue began. I have some midterm exams on this weekend. I would work on this after that. 
@arax-1238  @mskf1383 Meanwhile, if you can check if the issue exists when you build from source, and check when the issue started to appear, it would be very helpful.

**Comment by rafaelmardojai** [comment]
Yeah, it's probably caused by the new presets feature or the gobjects clean up. 

I also will try to check out.

**Comment by apandada1** [comment]
I just tested it in a Ubuntu 21.04 VM which has python 3.9.4. There the PPA version is working without any issue.

**Comment by rafaelmardojai** [comment]
Tested Blanket flatpak against `3.38` runtime that has python `3.8.8` and all works fine. You know what minor 3.8 python version  Ubuntu 20.04 has?

**Comment by Vectorvr10** [comment]
Ubuntu has python 3.8.10, I tried to run the daily version of the blanket ppa to see if it worked, it opened without showing any error in the terminal, but it did not load the icons or sound bars, it was just a blank screen that said "blanket ".
In my case, the stable version shows the same error that arax-1238 says, I don't know if installing a more modern python version will fix something, but I'm going to test.

**Comment by Vectorvr10** [comment]
Ok, I tried to run blanket with python3.9 (installation via apt with official Ubuntu repository) and the program doesn't work either, but it throws a different error, I don't know if it's important, but it's the following:

Traceback (most recent call last):
  File "/usr/bin/blanket", line 27, in <module>
    import gi
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 42, in <module>
    from . import _gi
ImportError: cannot import name '_gi' from partially initialized module 'gi' (most likely due to a circular import) (/usr/lib/python3/dist-packages/gi/__init__.py)
![image](https://user-images.githubusercontent.com/86861836/135552061-75598cc1-8086-4130-97c0-3c2068cca688.png)

**Comment by rafaelmardojai** [comment]
I really don't think it's a python issue, seems like something else.

**Comment by rafaelmardojai** [comment]
If someone could try building Blanket from source and checking out these commits in this order until it fails would be very awesome.

1. 76258c770043dacaab9ac85f0e96662372481312
2. 486a9603f779d3eb19d574c30670e9e9ce5ad1b8
3. 2e51a6eba240f1969c8d56aad91eb89325aeeda0
4. aa9cddffca06d6e7f08126ee98d03d472edbf550
5. bfd2f69290f06eb51baa14bd9461344c2dcbfe90
6. c0abfead5ce2068e6a856f41b7274d07d3f27d9d

**Comment by Mejans** [comment]
I have the behaviour Vectorvr10 describes, it opens but it is blank not blanket.

**Comment by rafaelmardojai** [comment]
@Helaxious could you try building from source from the commits listed above and see in what commit it fails?

**Comment by Helaxious** [comment]
Hey there, if I have done everything correctly, ( I'm still pretty new to this programing stuff  ) the second commit is the one failing for me, but just to be sure, I also tried the rest of the builds, here's what I've found out

1- `76258c7` - The app is working, but the dark mode doesn't seem to work for me, I'm not really sure why though.

2- `486a960`- The app is broken, if I try to start it with the terminal, it throws this error:

`(com.rafaelmardojai.Blanket:11839): Gtk-CRITICAL **: 14:50:58.347: Error building template class 'BlanketWindow' for an instance of type 'BlanketWindow': .:58:1 Invalid object type 'HdyFlap'
Traceback (most recent call last):
  File "/usr/local/share/blanket/blanket/main.py", line 128, in do_activate
    self.window = BlanketWindow(self.mainplayer, application=self)
  File "/usr/local/share/blanket/blanket/window.py", line 119, in __init__
    self.setup()
  File "/usr/local/share/blanket/blanket/window.py", line 128, in setup
    vol_adjustment = self.volume.get_adjustment()
AttributeError: 'NoneType' object has no attribute 'get_adjustment'`

If I try to launch the app with the terminal open ( the terminal behaves like the app is still open, even though the terminal doesn't open any window ) and close it, the terminal gives me these lines:

`Traceback (most recent call last):
  File "/usr/local/share/blanket/blanket/main.py", line 137, in do_activate
    self.window.update_playing_ui(Settings.get().playing)
  File "/usr/local/share/blanket/blanket/window.py", line 217, in update_playing_ui
    self.playpause_icon.set_from_icon_name(
AttributeError: 'NoneType' object has no attribute 'set_from_icon_name'`

But something a bit different than the 5.0 error I was getting, It doesn't show a top menu, and it's basically a blank window, it doesn't shows a minimize, maximize or close button too.

![Screenshot from 2021-10-08 14-47-52](https://user-images.githubusercontent.com/82718399/136621733-7c43a7de-8355-4d8c-aca3-c41fd849e3a6.png)


3- `2e51a6e` - It displays the same behavior, the error message is a bit different.

4- `aa9cddf` - Same behavior as the third commit.

5 - `bfd2f69` - This one shows a top menu, with the minimize, maximize, and close buttons and everything, I can use the menus and everything, but no contents, just like the 5.0 version. The terminal also gives me this error:

`Traceback (most recent call last):
  File "/usr/local/share/blanket/blanket/presets.py", line 48, in __init__
    self.presets_list.bind_model(self.model, self._create_widget)
AttributeError: 'Child' object has no attribute 'bind_model'
Traceback (most recent call last):
  File "/usr/local/share/blanket/blanket/main.py", line 140,
 in do_activate
    self.window = BlanketWindow(self.mainplayer, application=self)
  File "/usr/local/share/blanket/blanket/window.py", line 123, in __init__
    self.setup()
  File "/usr/local/share/blanket/blanket/window.py", line 151, in setup
    self.setup_presets()
  File "/usr/local/share/blanket/blanket/window.py", line 168, in setup_presets
    self.update_title(self.presets_chooser.selected)
  File "/usr/local/share/blanket/blanket/window.py", line 269, in update_title
    if preset.id != Settings.get().default_preset:
AttributeError: 'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "/usr/local/share/blanket/blanket/main.py", line 233, in _on_shutdown
    self._save_settings()
  File "/usr/local/share/blanket/blanket/main.py", line 216, in _save_settings
    Settings.get().scroll_position = self.window.vscroll.get_value()
AttributeError: 'BlanketWindow' object has no attribute 'vscroll'`

6 - `c0abfea` - Same behavior as the fifth commit.

**Comment by rafaelmardojai** [comment]
There isn't to my knowledge, you should check with your package manager.

**Comment by rafaelmardojai** [comment]
> Ah, ok, found it, running apt show libhandy-1-0 tells me that the version is 0.90.0-0~202009060346~ubuntu20.04.1

Yeah, that's the version packaged by @apandada1 for focal. But I just tested the Blanket's flatpak against `3.38` runtime + libhandy `0.90.0` and it works, so the issue isn't related to libhandy version.

**Comment by rafaelmardojai** [comment]
I'm installing an Ubuntu 20.04 VM and I will try to debug whats happening.

**Comment by SwampRabbit** [comment]
Blanket 0.5.0 up to #0d7f9f9 has no issue on MX Linux 21 RC1 (so Debian Bullseye), using libhandy-1-0 ver 1.0.3-2 and python 3.9.2-3.  I can build the latest, I just built what I pulled the other day.

I do think the Debian packaging needs some more work, its pulling in like 153MBs of -dev packages which is ridiculus.  I can help iron that out when I get some time, if @apandada1 wants some help with that.

**Comment by SwampRabbit** [comment]
> That is close to Ubuntu 21.04 right? We're having issues with Ubuntu 20.04.

I suppose it depends, I'm not Ubuntu package version expert but from 20.04 - 21.04 it "should" be based on Bullseye and Sid package versions, but that will vary from package to package depending on when they pulled from Sid.  Thats kinda the issue sometimes with Ubuntu, its not Debian Stable nor Sid, could be anywhere in the spectrum.

My "assumption" is that 20.04 would be on the lower end of Bullseye to Sid development.

I packaged Blanket 0.4.1 awhile ago for MX-19 which should be pretty close to Ubuntu 20.04, but I see that I used libhandy-1-0 ver 1.0.3-2 there too, but we have Debian Buster's Python 3.7.3 there.

I can try to build Blanket 0.5.0 against our MX-19, so libhandy-1-0 ver 1.0.3-2 and Python 3.7.3, to see if it has issues, its going to be a day or two though.

**Comment by apandada1** [comment]
>  153MBs of -dev packages which is ridiculous

We probably need to change [this](https://github.com/rafaelmardojai/blanket/blob/master/debian/control#L21) line to `libhandy-1-0` so that -dev packages are not pulled.


> the error from `486a960` is definitely because you need libhandy `1.2`. But in the final Blanket `0.5.0` release I don't think I'm using any libhandy feature that isn't present on `0.90.0`

The PPA has libhandy-1-0 0.90.0, and I can update that to 1.0.0. 
libhandy-1.2 is not compatible with Ubuntu 20.04 (has dependency issues).


> I can try to build Blanket 0.5.0 against our MX-19, so libhandy-1-0 ver 1.0.3-2 and Python 3.7.3, to see if it has issues, its going to be a day or two though.

Could you please try that? Ubuntu 20.04 has python 3.8.2, but still.

**Comment by SwampRabbit** [comment]
@apandada1 can do no problem, but its going to be about 12hrs before I can even try.

I'd move the libhandy-1-dev to the build depends, libhandy itself should get pulled in then as a runtime depends automagically.
I was surprised to see libhandy-1-dev in the runtime depends (seen stranger things), but I just started looking at the package, so wasn't going to do anything until I looked at it more.

**Comment by SwampRabbit** [comment]
So building for an updated MX-19 with libhandy-1-0 ver 1.0.3-2 and Python 3.7.3 (pretty close to Debian Buster) I get the following, which is very similar to what was reported earlier.
```
$ blanket
Traceback (most recent call last):
  File "/usr/share/blanket/blanket/presets.py", line 48, in __init__
    self.presets_list.bind_model(self.model, self._create_widget)
AttributeError: 'Child' object has no attribute 'bind_model'
Traceback (most recent call last):
  File "/usr/share/blanket/blanket/main.py", line 140, in do_activate
    self.window = BlanketWindow(self.mainplayer, application=self)
  File "/usr/share/blanket/blanket/window.py", line 123, in __init__
    self.setup()
  File "/usr/share/blanket/blanket/window.py", line 151, in setup
    self.setup_presets()
  File "/usr/share/blanket/blanket/window.py", line 168, in setup_presets
    self.update_title(self.presets_chooser.selected)
  File "/usr/share/blanket/blanket/window.py", line 254, in update_title
    if preset.id != Settings.get().default_preset:
AttributeError: 'NoneType' object has no attribute 'id'
```
Building and running on MX-21 RC1 (Debian Bullseye) is fine.

**Comment by apandada1** [comment]
Is there any way to test the source package with different python versions?

**Comment by Helaxious** [comment]
With linux mint 20.2 Cinammon I've got Blanket to build and compile with python 3.9.7 with `virtualvenv` and it shows me this error:
```
Traceback (most recent call last):
  File "/usr/local/bin/blanket", line 27, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'
```
It's similar to the error @Vectorvr10 had with python 3.9, this time though, It doesn't open any window if I try to launch it without the terminal

**Comment by Vectorvr10** [comment]
Not the best solution that could exist, but to use blanket, install version 0.4.1 ~ ubuntu20.10.1 on Ubuntu 20.04 alongside libhandy-1 and it works without any problem. To at least be able to use the program.

**Comment by apandada1** [comment]
Another issue is that, launchpad does not allow to downgrade, otherwise, I
would have pushed the previous version for Ubuntu 20.04.

**Comment by apandada1** [comment]
As a workaround, I pushed version 0.4.1 as `1:0.4.1` (Launchpad/apt thinks 1:0.4.1 > 0.5.0-1) only for 20.04, and people should get an update.

**Comment by apandada1** [comment]
Can we close this? It seems that the latest version is not compatible with Ubuntu 20.04. Now there is a working version (0.4.1) in the PPA, and one needs to use flatpak to get the latest version.

**Comment by arax-1238** [comment]
yes, you can close. I'm using 0.4.1 on Ubuntu 20.04 and it works perfectly!  Thanks.
